<?php

namespace Database\Seeders;

use App\Models\Event;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = [
            [
                'title' => 'Webinar AI 2025',
                'description' => 'Pembahasan tren AI terbaru',
                'category_id' => 1,
                'event_type' => 'webinar',
                'start_date' => now()->toDateString(),
                // 'end_date' => now()->toDateString(),
                'end_date' => now()->addDays(1)->toDateString(),
                'start_time' => '09:00',
                'end_time' => '12:00',
                'is_online' => true,
                'meeting_link' => 'https://zoom.us/example',
                'price' => 0,
                'benefits' => ['Masa aktif 1 tahun', 'E-Sertifikat', 'Akses ke materi'],
            ],
            [
                'title' => 'Workshop Android Kotlin',
                'description' => 'Belajar Android Kotlin dari dasar',
                'category_id' => 1,
                'event_type' => 'workshop',
                'start_date' => now()->addDays(3)->toDateString(),
                'start_time' => '10:00',
                'end_time' => '16:00',
                'is_online' => false,
                'location' => 'Jakarta',
                'price' => 150000,
                'benefits' => ['E-Sertifikat', 'Source Code', 'Akses Materi'],
            ],
            [
                'title' => 'Workshop Laravel',
                'description' => 'Belajar Laravel dari dasar',
                'category_id' => 1,
                'event_type' => 'workshop',
                'start_date' => now()->addDays(7)->toDateString(),
                'start_time' => '10:00',
                'end_time' => '16:00',
                'is_online' => false,
                'location' => 'Jakarta',
                'price' => 200000,
                'benefits' => ['E-Sertifikat', 'Source Code', 'Akses Materi'],
            ],
            [
                'title' => 'Workshop React',
                'description' => 'Belajar React dari dasar',
                'category_id' => 1,
                'event_type' => 'workshop',
                'start_date' => now()->addDays(14)->toDateString(),
                'start_time' => '10:00',
                'end_time' => '16:00',
                'is_online' => false,
                'location' => 'Jakarta',
                'price' => 250000,
                'benefits' => ['E-Sertifikat', 'Source Code', 'Akses Materi'],
            ],
            [
                'title' => 'Webinar UI/UX Design',
                'description' => 'Dasar UI/UX untuk pemula',
                'category_id' => 2,
                'event_type' => 'webinar',
                'start_date' => now()->addDays(5)->toDateString(),
                'start_time' => '13:00',
                'end_time' => '15:00',
                'is_online' => true,
                'meeting_link' => 'https://zoom.us/uiux',
                'price' => 0,
                'benefits' => ['E-Sertifikat', 'Recording'],
            ],
            [
                'title' => 'Bootcamp Fullstack Web',
                'description' => 'Bootcamp intensif fullstack developer',
                'category_id' => 1,
                'event_type' => 'workshop',
                'start_date' => now()->addDays(10)->toDateString(),
                'start_time' => '09:00',
                'end_time' => '17:00',
                'is_online' => false,
                'location' => 'Bandung',
                'price' => 1500000,
                'benefits' => ['Sertifikat', 'Portfolio Project', 'Mentoring'],
            ],
            [
                'title' => 'Webinar Cyber Security',
                'description' => 'Pengenalan keamanan sistem',
                'category_id' => 3,
                'event_type' => 'webinar',
                'start_date' => now()->addDays(6)->toDateString(),
                'start_time' => '19:00',
                'end_time' => '21:00',
                'is_online' => true,
                'meeting_link' => 'https://zoom.us/cyber',
                'price' => 50000,
                'benefits' => ['E-Sertifikat', 'Materi PDF'],
            ],
            [
                'title' => 'Workshop Data Science',
                'description' => 'Belajar data science dengan Python',
                'category_id' => 3,
                'event_type' => 'workshop',
                'start_date' => now()->addDays(12)->toDateString(),
                'start_time' => '09:00',
                'end_time' => '16:00',
                'is_online' => false,
                'location' => 'Surabaya',
                'price' => 300000,
                'benefits' => ['E-Sertifikat', 'Notebook', 'Dataset'],
            ],
            [
                'title' => 'Webinar Cloud Computing',
                'description' => 'Pengenalan AWS & Cloud',
                'category_id' => 4,
                'event_type' => 'webinar',
                'start_date' => now()->addDays(8)->toDateString(),
                'start_time' => '15:00',
                'end_time' => '17:00',
                'is_online' => true,
                'meeting_link' => 'https://zoom.us/cloud',
                'price' => 0,
                'benefits' => ['E-Sertifikat', 'Materi'],
            ],
            [
                'title' => 'Workshop DevOps',
                'description' => 'CI/CD dan Docker untuk developer',
                'category_id' => 4,
                'event_type' => 'workshop',
                'start_date' => now()->addDays(20)->toDateString(),
                'start_time' => '09:00',
                'end_time' => '16:00',
                'is_online' => false,
                'location' => 'Jakarta',
                'price' => 400000,
                'benefits' => ['Sertifikat', 'Hands-on Project'],
            ],
            [
                'title' => 'Workshop Data Science',
                'description' => 'Belajar data science dengan Python',
                'category_id' => 3,
                'event_type' => 'workshop',
                'start_date' => now()->addDays(12)->toDateString(),
                'start_time' => '09:00',
                'end_time' => '16:00',
                'is_online' => false,
                'location' => 'Surabaya',
                'price' => 300000,
                'benefits' => ['E-Sertifikat', 'Notebook', 'Dataset'],
            ],
            [
                'title' => 'Workshop AI',
                'description' => 'Belajar AI dengan Python',
                'category_id' => 3,
                'event_type' => 'workshop',
                'start_date' => now()->addDays(20)->toDateString(),
                'start_time' => '09:00',
                'end_time' => '16:00',
                'is_online' => false,
                'location' => 'Jakarta',
                'price' => 400000,
                'benefits' => ['Sertifikat', 'Hands-on Project'],
            ],
            [
                'title' => 'Webinar Digital Marketing',
                'description' => 'Strategi digital marketing 2025',
                'category_id' => 2,
                'event_type' => 'webinar',
                'start_date' => now()->addDays(9)->toDateString(),
                'start_time' => '19:00',
                'end_time' => '21:00',
                'is_online' => true,
                'meeting_link' => 'https://zoom.us/marketing',
                'price' => 0,
                'benefits' => ['E-Sertifikat', 'Slide Materi'],
            ],
            [
                'title' => 'Workshop Machine Learning',
                'description' => 'Implementasi ML dengan Python',
                'category_id' => 3,
                'event_type' => 'workshop',
                'start_date' => now()->addDays(15)->toDateString(),
                'start_time' => '09:00',
                'end_time' => '16:00',
                'is_online' => false,
                'location' => 'Yogyakarta',
                'price' => 500000,
                'benefits' => ['Sertifikat', 'Project ML'],
            ],
            [
                'title' => 'Webinar Public Speaking',
                'description' => 'Skill komunikasi profesional',
                'category_id' => 2,
                'event_type' => 'webinar',
                'start_date' => now()->addDays(11)->toDateString(),
                'start_time' => '18:30',
                'end_time' => '20:30',
                'is_online' => true,
                'meeting_link' => 'https://zoom.us/speaking',
                'price' => 25000,
                'benefits' => ['E-Sertifikat'],
            ],
            [
                'title' => 'Workshop UI Design Figma',
                'description' => 'Design UI modern dengan Figma',
                'category_id' => 2,
                'event_type' => 'workshop',
                'start_date' => now()->addDays(18)->toDateString(),
                'start_time' => '10:00',
                'end_time' => '17:00',
                'is_online' => false,
                'location' => 'Jakarta',
                'price' => 350000,
                'benefits' => ['Sertifikat', 'File Design'],
            ],
            [
                'title' => 'Webinar Blockchain Basics',
                'description' => 'Pengenalan teknologi blockchain',
                'category_id' => 2,
                'event_type' => 'webinar',
                'start_date' => now()->addDays(16)->toDateString(),
                'start_time' => '20:00',
                'end_time' => '22:00',
                'is_online' => true,
                'meeting_link' => 'https://zoom.us/blockchain',
                'price' => 0,
                'benefits' => ['E-Sertifikat', 'Recording'],
            ],
            [
                'title' => 'Workshop AI',
                'description' => 'Belajar AI dengan Python',
                'category_id' => 3,
                'event_type' => 'workshop',
                'start_date' => now()->addDays(20)->toDateString(),
                'start_time' => '09:00',
                'end_time' => '16:00',
                'is_online' => false,
                'location' => 'Jakarta',
                'price' => 400000,
                'benefits' => ['Sertifikat', 'Hands-on Project'],
            ],
        ];

        foreach ($events as $event) {
            Event::create($event);
        }
    }
}
